services:
  app:
    image: node-tarpit-dev
    hostname: node-tarpit
    command: sleep infinity
    volumes:
      - ..:/workspace/node-tarpit:cached
      - node-tarpit-pnpm-store:/root/.local/share/pnpm/store
      - ${HOME}/.config/gh:/root/.config/gh:ro
      - ${HOME}/.node-tarpit/zsh_history:/root/.zsh_history_persist
      - ${SSH_AUTH_SOCK}:/tmp/ssh-agent.sock
      - ${HOME}/.ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
      - "7022:22"
    environment:
      # CI: "true"
      MONGODB_URL: mongodb://admin:admin_password@mongo:27017/test?authSource=admin
      RABBITMQ_URL: amqp://admin:admin_password@rabbitmq:5672
      TPKIT_STORE_URL:
      COLORTERM: truecolor
      FORCE_COLOR: "1"
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
      HTTPS_PROXY: http://host.docker.internal:6152
      HTTP_PROXY: http://host.docker.internal:6152
      NO_PROXY: localhost,127.0.0.1,mongo,rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:8
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin_password

volumes:
  node-tarpit-pnpm-store:
  mongo-data:
