# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn lerna bootstrap
      - run: yarn lerna run build
      - run: yarn lerna run test

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: |
            ./packages/barbeque/coverage/coverage-final.json,
            ./packages/config/coverage/coverage-final.json,
            ./packages/dora/coverage/coverage-final.json,
            ./packages/error/coverage/coverage-final.json,
            ./packages/judge/coverage/coverage-final.json,
            ./modules/content-type/coverage/coverage-final.json,
            ./modules/core/coverage/coverage-final.json,
            ./modules/http/coverage/coverage-final.json

