name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
    services:
      rabbitmq:
        image: rabbitmq:3.9
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin_password
        ports:
          - 5672/tcp
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: lerna run build

      - name: Test
        env:
          RABBITMQ_URL: amqp://admin:admin_password@localhost:${{ job.services.rabbitmq.ports[5672] }}
        run: lerna run test --verbose

      - name: Upload coverage files
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./actions/upload-codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
