# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn lerna bootstrap
      - run: "yarn lerna run build --scope \"@tarpit/abraham\""
      - run: "yarn lerna run build --ignore \"@tarpit/abraham\""
      - run: yarn lerna run test

      - name: Upload coverage barbeque
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: barbeque
          fail_ci_if_error: true
          files: ./packages/barbeque/coverage/coverage-final.json

      - name: Upload coverage config
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: config
          fail_ci_if_error: true
          files: ./packages/config/coverage/coverage-final.json

      - name: Upload coverage dora
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: dora
          fail_ci_if_error: true
          files: ./packages/dora/coverage/coverage-final.json

      - name: Upload coverage error
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: error
          fail_ci_if_error: true
          files: ./packages/error/coverage/coverage-final.json,

      - name: Upload coverage judge
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: judge
          fail_ci_if_error: true
          files: ./packages/judge/coverage/coverage-final.json

      - name: Upload coverage content-type
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: content-type
          fail_ci_if_error: true
          files: ./modules/content-type/coverage/coverage-final.json

      - name: Upload coverage core
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: core
          fail_ci_if_error: true
          files: ./modules/core/coverage/coverage-final.json

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          tags: http
          fail_ci_if_error: true
          files: ./modules/http/coverage/coverage-final.json
