name: node-tarpit-dev

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 16.x

    services:
      rabbitmq:
        image: rabbitmq:3.9
        env:
          RABBITMQ_DEFAULT_USER: admin
          RABBITMQ_DEFAULT_PASS: admin_password
        ports:
          - 5672

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure CI Git User
        run: |
          git config --global user.name isatiso
          git config --global user.email sieglive@gmail.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/isatiso/node-tarpit.git

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - env:
          RABBITMQ_USER: admin
          RABBITMQ_PASSWORD: admin_password
          RABBITMQ_HOST: 127.0.0.1
        run: |
          yarn install
          yarn lerna bootstrap
          yarn lerna run build --scope "@tarpit/abraham"
          yarn lerna run build --ignore "@tarpit/abraham"
          yarn lerna run test

      - name: Upload coverage barbeque
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: barbeque
          fail_ci_if_error: true
          files: ./packages/barbeque/coverage/coverage-final.json

      - name: Upload coverage config
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: config
          fail_ci_if_error: true
          files: ./packages/config/coverage/coverage-final.json

      - name: Upload coverage dora
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: dora
          fail_ci_if_error: true
          files: ./packages/dora/coverage/coverage-final.json

      - name: Upload coverage error
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: error
          fail_ci_if_error: true
          files: ./packages/error/coverage/coverage-final.json

      - name: Upload coverage judge
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: judge
          fail_ci_if_error: true
          files: ./packages/judge/coverage/coverage-final.json

      - name: Upload coverage content-type
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: content-type
          fail_ci_if_error: true
          files: ./modules/content-type/coverage/coverage-final.json

      - name: Upload coverage core
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: core
          fail_ci_if_error: true
          files: ./modules/core/coverage/coverage-final.json

      - name: Upload coverage http
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: http
          fail_ci_if_error: true
          files: ./modules/http/coverage/coverage-final.json

      - name: Upload coverage schedule
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: schedule
          fail_ci_if_error: true
          files: ./modules/http/coverage/coverage-final.json
