name: Deploy Docusaurus Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        working-directory: ./docs
        run: |
          echo "Installing Docusaurus dependencies..."
          yarn install --frozen-lockfile
          echo "Dependencies installed successfully"

      - name: Build Docusaurus
        working-directory: ./docs
        run: |
          echo "Building Docusaurus site..."
          yarn build
          echo "Build completed successfully"
          echo "Generated files:"
          ls -la build/
        env:
          NODE_ENV: production

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
