name: publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile

      - name: Build
        run: lerna run build

      - name: Configure CI Git User
        run: |
          git config --global user.name isatiso
          git config --global user.email sieglive@gmail.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/isatiso/node-tarpit.git

      - name: Publish package
        run: |
          lerna publish --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
