name: publish

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Configure CI Git User
        run: |
          git config --global user.name "Plank Cao"
          git config --global user.email sieglive@gmail.com
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/isatiso/node-tarpit.git

      - name: Publish package
        run: |
          pnpm config set -- '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          pnpm -r build
          pnpm version patch -m "chore(release): publish %s"
          pnpm -r publish --no-git-checks
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
